# -*- coding: utf-8 -*-
namespace :ios do
  $:.unshift('/Library/RubyMotion/lib')
  require 'motion/project/template/ios'
  require 'bundler'

  Bundler.require :default, :ios

  Dir.chdir 'ios'

  Motion::Project::App.setup do |app|
    # Use `rake config' to see complete project settings.
    app.name = 'Define'
    app.deployment_target = '7.0'
    app.device_family = [:iphone, :ipad]
    app.interface_orientations = [:portrait, :portrait_upside_down]
    app.identifier = 'com.k2b6s9j.Define'
    app.short_version = '2.0'
    app.icons = Dir.glob('resources/Icon*.png').map{|icon| icon.split('/').last}
    app.prerendered_icon = true
    app.info_plist['APP_STORE_ID'] = 564677354
    app.info_plist['CFBundleURLTypes'] = [
        { 'CFBundleURLName' => 'com.k2b6s9j.Define',
          'CFBundleURLSchemes' => ['define'] }
    ]

    app.files << (FileList.new('app/**/*.rb', 'test/test*.rb').exclude('app/phrase_config.rb'))
    app.files << Dir.glob('../lib/**/*.rb')

    app.pods do
      pod 'FlurrySDK'
    end

    app.development do
      app.phrase do
        app.phrase.enabled = true
        app.phrase.auth_token = 'eeddef8fbe65f23300c674fc23a1d4ee'
      end

      app.entitlements['get-task-allow'] = true
      app.codesign_certificate = 'iPhone Developer: Kepler Sticka-Jones (XC4RK3W595)'
      app.provisioning_profile = './provisioning/Define_Mobile_Development_Profile.mobileprovision'
    end

  end

  #Build Task Dependencies
  task :build => 'ios:phrase:pull'
  task 'build:device' => 'ios:phrase:pull'
  task 'build:simulator' => 'ios:phrase:pull'
end